#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
cleanCase

rm -rf ./0
rm -rf constant/polyMesh
rm *.foam > /dev/null

# rm log.*
# rm -rf postProcessing
# rm -rf processor*
