#!/bin/sh
state=0
while IFS= read -r line; do
    case "${line// }" in
        AMI[12]) state=${line##*AMI}
                 echo "$line";;
        typepatch\;*) if [ "$state" != 0 ]; then
                          echo "        type            cyclicAMI;"
                          echo "        inGroups        1(cyclicAMI);"
                      else
                          echo "$line"
                      fi;;
        \}) if [ "$state" != 0 ]; then
                echo "        matchTolerance  0.0001;"
                echo "        transform       noOrdering;"
                echo "        neighbourPatch  AMI$((3-state));"
                echo "    }"
                state=0
            else
                echo "    }"
            fi;;
        *) echo "$line"
    esac
done < constant/polyMesh/boundary > boundary.tmp
cp -f boundary.tmp constant/polyMesh/boundary
rm boundary.tmp
