#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


m4 -P blockMeshDict.m4 > system/blockMeshDict

runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication decomposePar
runParallel snappyHexMesh -overwrite
runApplication reconstructParMesh -constant
runApplication renumberMesh -overwrite
touch ${PWD##*/}.foam
rm -rf processor*
