#!/bin/sh
#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
cleanCase
rm -rf 0

# rm log.*
# rm *.foam
# rm -rf constant/polyMesh
# rm -rf postProcessing
# rm -rf processor*
