#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -rf ../fix_domain/constant/polyMesh ./constant/
mergeMeshes ./ ../mob_domain -overwrite
renumberMesh -overwrite
./setAmi
topoSet

cp -rf 0.org 0

#---------------------------------------# 
#               PARALELO                #
#---------------------------------------# 
decomposePar
# mpiexec -n 4 pimpleDyMFoam -parallel
mpiexec -n 4 moveDynamicMesh -parallel
# runParallel pimpleDyMFoam
# runParallel moveDynamicMesh
#--------------------------------------#


#-----------------------------------# 
#           NO PARALELO             #
#-----------------------------------# 
# moveDynamicMesh
# pimpleDyMFoam

touch ${PWD##*/}.foam